hostname: wiki.ropecon.fi
redis:
  database: 6
s3:
  bucket: outlineropecon
kompassi:
  teamName: Ropecon
  accessGroups:
    - turska-ropecon2026-labour-conitea
    - turska-ropecon2026-labour-turvan-sihteerit
    - turska-ropecon2026-labour-info
    - turska-ropecon2026-labour-jv
    - turska-ropecon2026-labour-accepted
    - ropecon2026-program-hosts
    - ropeconry-hallitus-nykyinen
