apiVersion: v1
kind: Secret
metadata:
  name: outline
  labels:
    app.kubernetes.io/part-of: outline
type: Opaque
data:
  awsAccessKeyId: ''
  awsSecretAccessKey: ''
  kompassiClientId: ''
  kompassiClientSecret: ''
  secretKey: !Base64,Var outline_secret_key
  utilsSecretKey: !Base64,Var outline_utils_secret_key
