apiVersion: v1
kind: Secret
metadata:
  name: outline
  labels:
    app.kubernetes.io/part-of: outline
  annotations: !If
    test: !Not,Var outline_secret_key
    then:
      secret-generator.v1.mittwald.de/autogenerate: secretKey
type: Opaque
data: !If
  test: !Var outline_secret_key
  then:
    secretKey: !Base64,Var outline_secret_key
  else: {}
