apiVersion: v1
kind: Secret
metadata:
  name: outline
  labels:
    app.kubernetes.io/part-of: outline
  annotations: !If
    test: !Not,All [!Var outline_secret_key, !Var smtp_password]
    then:
      secret-generator.v1.mittwald.de/autogenerate: !Join
        separator: ","
        items:
          - !If
              test: !Var outline_secret_key
              then: !Void
              else: secretKey
          - !If
              test: !Var smtp_password
              then: !Void
              else: smtpPassword
type: Opaque
data: !Merge
  - !If
      test: !Var outline_secret_key
      then:
        secretKey: !Base64,Var outline_secret_key
  - !If
      test: !Var smtp_password
      then:
        smtpPassword: !Base64,Var smtp_password