apiVersion: v1
kind: Service
metadata:
  name: outline
  labels:
    app.kubernetes.io/part-of: outline
    app.kubernetes.io/name: outline
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/part-of: outline
    app.kubernetes.io/name: outline
