# syntax=docker/dockerfile:1.2

ARG UPSTREAM_IMAGE
ARG APP_PATH=/opt/outline
FROM $UPSTREAM_IMAGE as base

ARG APP_PATH
WORKDIR $APP_PATH

# ---
FROM node:16.14.2-alpine3.15 AS runner

ARG APP_PATH
WORKDIR $APP_PATH
ENV NODE_ENV production

COPY --from=base $APP_PATH/build ./build
COPY --from=base $APP_PATH/server ./server
COPY --from=base $APP_PATH/public ./public
COPY --from=base $APP_PATH/.sequelizerc ./.sequelizerc
COPY --from=base $APP_PATH/node_modules ./node_modules
COPY --from=base $APP_PATH/package.json ./package.json

RUN addgroup -g 1001 -S nodejs && \
  adduser -S nodejs -u 1001 && \
  chown -R nodejs:nodejs $APP_PATH/build

ADD --chmod=0755 docker-entrypoint.sh /opt/outline/


USER nodejs

EXPOSE 3000
ENTRYPOINT ["/opt/outline/docker-entrypoint.sh"]
CMD ["node", "./build/server/index.js"]
