#!/bin/bash

set -ue

# Allow setting either DATABASE_URL (takes precedence) or OUTLINE_POSTGRESQL_*
OUTLINE_POSTGRESQL_USERNAME="${OUTLINE_POSTGRESQL_USERNAME:-outline}"
OUTLINE_POSTGRESQL_PASSWORD="${OUTLINE_POSTGRESQL_PASSWORD:-secret}"
OUTLINE_POSTGRESQL_HOSTNAME="${OUTLINE_POSTGRESQL_HOSTNAME:-postgres}"
OUTLINE_POSTGRESQL_DATABASE="${OUTLINE_POSTGRESQL_DATABASE:-outline}"
export DATABASE_URL="${DATABASE_URL:-postgres://$OUTLINE_POSTGRESQL_USERNAME:$OUTLINE_POSTGRESQL_PASSWORD@$OUTLINE_POSTGRESQL_HOSTNAME/$OUTLINE_POSTGRESQL_DATABASE}"

exec "$@"
