#!/bin/bash

set -ue

# Allow setting either DATABASE_URL (takes precedence) or POSTGRES_*
POSTGRES_USERNAME="${POSTGRES_USERNAME:-outline}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-secret}"
POSTGRES_HOSTNAME="${POSTGRES_HOSTNAME:-postgres}"
POSTGRES_DATABASE="${POSTGRES_DATABASE:-outline}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_SSL="${POSTGRES_SSL:-false}"
export DATABASE_URL="${DATABASE_URL:-postgres://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOSTNAME:$POSTGRES_PORT/$POSTGRES_DATABASE?ssl=$POSTGRES_SSL}"

exec "$@"
