apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "outline.fullname" . }}-migrate
  labels:
    {{- include "outline.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ include "outline.serviceAccountName" . }}
      enableServiceLinks: false
      restartPolicy: OnFailure
      containers:
        - name: {{ .Chart.Name }}-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - yarn
            - sequelize:migrate
            - --env=production
          volumeMounts:
            - mountPath: /home/outline
              name: outline-temp
          env:
            {{- include "outline.env" . | nindent 12 }}
      volumes:
        - name: outline-temp
          emptyDir:
            medium: Memory
