apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app.kubernetes.io/part-of: outline
    app.kubernetes.io/component: database
    app.kubernetes.io/name: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: outline
      app.kubernetes.io/component: database
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: outline
        app.kubernetes.io/component: database
        app.kubernetes.io/name: redis
    spec:
      enableServiceLinks: false
      containers:
        - name: redis
          image: !Var redis_image
          args:
            - redis-server
            - "--appendonly"
            - "yes"
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
