apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
    app.kubernetes.io/part-of: outline
    app.kubernetes.io/component: database
    app.kubernetes.io/name: redis-data
spec:
  storageClass: !Var postgres_storage_pvc_storageclass
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
