apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/part-of: outline
    app.kubernetes.io/component: database
    app.kubernetes.io/name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/part-of: outline
    app.kubernetes.io/component: database
    app.kubernetes.io/name: redis