apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: outline
  annotations: !Var ingress_annotations
spec:
  tls: !Var ingress_tls
  rules:
    - host: !Var ingress_public_hostname
      http:
        paths:
          - path: /
            backend:
              serviceName: outline
              servicePort: 3000
