name: cicd

on:
  push:
    branches:
      - con2

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SKAFFOLD_DEFAULT_REPO: ghcr.io/con2
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.x"
      - id: cache-bin
        uses: actions/cache@v6
        with:
          path: bin
          key: ${{ runner.os }}-bin-3
      - if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          mkdir bin
          curl -Lo bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          curl -Lo bin/kubectl https://dl.k8s.io/release/v1.36.2/bin/linux/amd64/kubectl
          chmod +x bin/skaffold bin/kubectl
      - run: echo "$PWD/bin" >> $GITHUB_PATH
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - uses: docker/setup-buildx-action@v4
      - id: build
        run: |
          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install emskaffolden
          emskaffolden -- build --file-output build.json
      - uses: actions/upload-artifact@v7
        with:
          name: build-json
          path: build.json

  deploy:
    runs-on: qb-arc-runners
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/con2' }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: build-json
      - uses: actions/setup-python@v7
        with:
          python-version: "3.x"
      - id: cache-bin
        uses: actions/cache@v6
        with:
          path: bin
          key: ${{ runner.os }}-bin-3
      - if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          mkdir bin
          curl -Lo bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          curl -Lo bin/kubectl https://dl.k8s.io/release/v1.36.2/bin/linux/amd64/kubectl
          chmod +x bin/skaffold bin/kubectl
      - run: echo "$PWD/bin" >> $GITHUB_PATH
      - run: |
          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install emskaffolden
          emskaffolden -E con2 -- deploy -n outline -a build.json
          emskaffolden -E tracon -- deploy -n outline-tracon -a build.json
          emskaffolden -E kuplii -- deploy -n outline-kuplii -a build.json
          emskaffolden -E ropecon -- deploy -n outline-ropecon -a build.json
          emskaffolden -E kotae -- deploy -n outline-kotae -a build.json
