apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/part-of: outline
    app.kubernetes.io/name: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/part-of: outline
    app.kubernetes.io/name: postgres
